name: Daily Standard Ebooks JSON by Genre

on:
  schedule:
    # every day at 00:05 UTC
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet jq

      - name: Fetch OPDS & build books.json
        env:
          OPDS_KEY: ${{ secrets.OPDS_KEY }}
        run: |
          set -eux

          # list of genres to include
          GENRES=(
            Adventure
            Autobiography
            Biography
            "Children’s"
            Comedy
            Drama
            Fantasy
            Fiction
            Horror
            Memoir
            Mystery
            Nonfiction
            Philosophy
            Poetry
            Satire
            "Science Fiction"
            Shorts
            Spirituality
            Travel
          )

          # fetch the OPDS feed
          curl -u "$OPDS_KEY:" -sS https://standardebooks.org/feeds/opds/all > feed.xml

          # start JSON array
          echo "[" > books.json
          first=true

          for GENRE in "${GENRES[@]}"; do
            # namespace-agnostic XPath for entries tagged with this subject
            SUBJECT_XPATH="//*[local-name()='entry' and .//*[local-name()='category' and @scheme='https://standardebooks.org/vocab/subjects' and @term=\"$GENRE\"]]"

            # count how many entries match
            COUNT=$(xmlstarlet sel -t -v "count(${SUBJECT_XPATH})" feed.xml)
            [ "$COUNT" -gt 0 ] || continue

            # pick one seeded by date
            IDX=$(( (10#$(date -u +%Y%m%d) % COUNT) + 1 ))

            # extract that entry
            xmlstarlet sel -t -c "(${SUBJECT_XPATH})[$IDX]" feed.xml > entry.xml

            # pull fields
            TITLE=$(xmlstarlet sel -t -v "string(//*[local-name()='title'])" entry.xml | jq -R -s 'rtrimstr("\n")')
            AUTHOR=$(xmlstarlet sel -t -v "string(//*[local-name()='author']/*[local-name()='name'])" entry.xml | jq -R -s 'rtrimstr("\n")')
            SUMMARY=$(xmlstarlet sel -t -v "string(//*[local-name()='summary'])" entry.xml | jq -R -s 'rtrimstr("\n")')
            COVER=$(xmlstarlet sel -t -v "string(//*[local-name()='link' and @rel='http://opds-spec.org/image']/@href)" entry.xml)
            ENTRY_URL=$(xmlstarlet sel -t -v "string(//*[local-name()='id'])" entry.xml)

            # build JSON object
            OBJ=$(jq -n \
              --arg genre    "$GENRE" \
              --arg date     "$(date -u +%F)" \
              --argjson title   "$TITLE" \
              --argjson author  "$AUTHOR" \
              --argjson summary "$SUMMARY" \
              --arg coverUrl    "$COVER" \
              --arg entryUrl    "$ENTRY_URL" \
              '{
                 genre:   $genre,
                 date:    $date,
                 title:   $title,
                 author:  $author,
                 summary: $summary,
                 coverUrl: $coverUrl,
                 entryUrl: $entryUrl
               }')

            # append comma if not first
            if $first; then
              first=false
            else
              echo "," >> books.json
            fi

            # append the object
            echo "$OBJ" >> books.json
          done

          # close JSON array
          echo "]" >> books.json

      - name: Commit & push books.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add books.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily books JSON $(date -u +%F)"
            git push
          fi
