name: Daily Standard Ebooks JSON

on:
  schedule:
    - cron: '5 0 * * *'   # every day at 00:05 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install XML tools
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet

      - name: Fetch & parse OPDS → today.json
        env:
          OPDS_KEY: ${{ secrets.OPDS_KEY }}
        run: |
          set -eux

          # 1. Download feed
          curl -u "$OPDS_KEY:" -sS https://standardebooks.org/feeds/opds/all > feed.xml

          # 2. Count entries
          TOTAL=$(xmlstarlet sel -t -v "count(//entry)" feed.xml)

          # 3. Compute index: (YYYYMMDD mod TOTAL) + 1
          IDX=$(( (10#$(date -u +%Y%m%d) % TOTAL) + 1 ))

          # 4. Extract the Nth <entry> into a temp file
          xmlstarlet sel -t -c "(//entry)[$IDX]" feed.xml > entry.xml

          # 5. Pull fields
          TITLE=$(xmlstarlet sel -t -v "//title" entry.xml)
          AUTHOR=$(xmlstarlet sel -t -v "//author/name" entry.xml)
          SUMMARY=$(xmlstarlet sel -t -v "//summary" entry.xml | sed 's/"/\\"/g')
          COVER=$(xmlstarlet sel -t -v "//link[@rel='http://opds-spec.org/image/thumbnail']/@href" entry.xml)
          EPUB=$(xmlstarlet sel -t -v "//link[@type='application/epub+zip']/@href" entry.xml)
          SUBJECTS=$(xmlstarlet sel -t -m "//category" -v "@term" -n entry.xml | jq -R -s 'split("\n") | map(select(length>0))')

          # 6. Write JSON
          cat > today.json <<EOF
          {
            "date": "$(date -u +%Y-%m-%d)",
            "title":   "${TITLE}",
            "author":  "${AUTHOR}",
            "summary": "${SUMMARY}",
            "coverUrl": "${COVER}",
            "epubUrl":  "${EPUB}",
            "subjects": ${SUBJECTS}
          }
          EOF

      - name: Commit & Push today.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add today.json
          git diff --quiet && echo "No change – skipping commit" || git commit -m "Daily book JSON for $(date -u +%Y-%m-%d)" && git push
