name: Daily Standard Ebooks JSON

on:
  schedule:
    - cron: '5 0 * * *'   # every day at 00:05 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install XML & JSON tools
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet jq

      - name: Fetch & parse OPDS → today.json
        env:
          OPDS_KEY: ${{ secrets.OPDS_KEY }}
        run: |
          set -eux

          # 1. Download feed
          curl -u "$OPDS_KEY:" -sS https://standardebooks.org/feeds/opds/all > feed.xml

          # 2. Count entries (use local-name() to ignore namespaces)
          TOTAL=$(xmlstarlet sel -t -v "count(//*[local-name()='entry'])" feed.xml)

          # 3. Compute index: (YYYYMMDD mod TOTAL) + 1
          IDX=$(( (10#$(date -u +%Y%m%d) % TOTAL) + 1 ))

          # 4. Extract the Nth <entry>
          xmlstarlet sel -t -c "(//*[local-name()='entry'])[$IDX]" feed.xml > entry.xml

          # 5. Pull fields
          TITLE=$(xmlstarlet sel -t -v "//*[local-name()='title']" entry.xml)
          AUTHOR=$(xmlstarlet sel -t -v "//*[local-name()='author']/*[local-name()='name']" entry.xml)
          SUMMARY=$(xmlstarlet sel -t -v "//*[local-name()='summary']" entry.xml | sed 's/"/\\"/g')
          COVER=$(xmlstarlet sel -t -v "//*[local-name()='link' and @rel='http://opds-spec.org/image/thumbnail']/@href" entry.xml)
          EPUB=$(xmlstarlet sel -t -v "//*[local-name()='link' and @type='application/epub+zip']/@href" entry.xml)
          SUBJECTS=$(xmlstarlet sel -t -m "//*[local-name()='category']" -v "@term" -n entry.xml | jq -R -s 'split("\n") | map(select(length>0))')

          # 6. Write out clean JSON
          cat > today.json <<EOF
{
  "date": "$(date -u +%Y-%m-%d)",
  "title": "${TITLE}",
  "author": "${AUTHOR}",
  "summary": "${SUMMARY}",
  "coverUrl": "${COVER}",
  "epubUrl": "${EPUB}",
  "subjects": ${SUBJECTS}
}
EOF

      - name: Commit & Push today.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add today.json
          if git diff --quiet; then
            echo "No change – skipping commit"
          else
            git commit -m "Daily book JSON for $(date -u +%Y-%m-%d)"
            git push
          fi
